#!/bin/csh -f

#Runscript to use in Hoffman2 at UCLA
#SGE-specific settings
#$ -l highp,h_data=2G,h_rt=72:00:00
#$ -V
#$ -cwd
#$ -m abe
#$ -q mitch_pod.q

#Minimal runscript for atmospheric dynamical cores
set echo
#--------------------------------------------------------------------------------------------------------
# define variables
set basedir   = ~/hab_proj/Isca/exp/myexps # A base directory with code
set exp_file  = tam_noinf_bd10m_es01p75_rot16d.py
set condadir  = ~/miniconda/bin                         # Conda directory
##--------------------------------------------------------------------------------------------------------

source $condadir/activate.csh isca_env
python $basedir/$exp_file
